version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      # Phoenix Configuration
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      PHX_HOST: ${PHX_HOST:-localhost}
      PORT: ${PORT:-4000}

      # Cloudflare API Configuration
      CLOUDFLARE_TOKEN: ${CLOUDFLARE_TOKEN}
      CLOUDFLARE_ZONE: ${CLOUDFLARE_ZONE}
      CLOUDFLARE_DOMAIN: ${CLOUDFLARE_DOMAIN}

      # Authentication
      ACCESS_PASSWORD: ${ACCESS_PASSWORD}

      # Optional: DNS Cluster
      DNS_CLUSTER_QUERY: ${DNS_CLUSTER_QUERY:-}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
